FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl ca-certificates curl && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

RUN corepack enable
RUN yarn install --immutable

# Prisma Client + Next build im Image
COPY . .
RUN yarn prisma generate
RUN yarn build

EXPOSE 3000
ENV NODE_ENV=production
